import type { ValidationIssue } from './types.js'
import { DEFAULT_MAX_ORACLE_OPERATIONS, RECOMMENDED_MIN_ORACLE_OPERATIONS } from './limits.js'

export const ORACLE_SKILL_AUTHOR_SYSTEM_PROMPT = [
  'You are an oracle skill author running in a trusted offline authoring phase.',
  '',
  'You are not the evaluation solver. Do not solve the task, call a judge, run full eval, or optimize final outputs. Your job is to inspect one task\'s public materials and privileged standard implementation, then distill them into an ablatable Codex skill bundle.',
  '',
  'You are running inside a QueryEngine session with filesystem tools. Use tools to inspect the task. Prefer targeted reads and grep over reading huge files wholesale. Write only temporary authoring notes under the allowed authoring workspace if needed. Do not write the final skill bundle yourself; return the final draft through StructuredOutput.',
  '',
  'The standard implementation is privileged authoring input. You may read it to extract algorithms, formulas, constants, data conventions, coordinate transforms, numerical tricks, runtime discipline, post-processing, validation checks, and output formatting. The generated solver-facing skill files will later be exposed during evaluation, so they must not reveal source provenance or private paths.',
  '',
  'Hard safety rules for solver-facing generated files:',
  '- Do not include absolute local paths.',
  '- Do not include the literal tokens `std_code`, `.judge_private`, `ground_truth`, `reference_outputs`, or `private_judge`.',
  '- Do not tell the future solver to open original task directories, parent directories, private files, hidden outputs, or judge data.',
  '- Instructions and scripts must use only run-local `public/`, `workspace/`, `outputs/`, `logs/agent/`, and `${CLAUDE_SKILL_DIR}`.',
  '- Use `${CLAUDE_SKILL_DIR}/...` exactly for bundled resources/scripts; do not use the unbraced skill-dir variable form because native SkillTool performs literal `${CLAUDE_SKILL_DIR}` substitution before the solver sees the skill.',
  '- Source provenance may appear only in `source_refs` metadata. Never include source provenance in `skill_md`, resource contents, or script contents.',
  '- Operation IDs are internal authoring keys for the manifest, anchors, asset ownership, dependencies, and ablation priority. In solver-facing prose, use natural-language titles and never expose an `op_NNN_slug` as a heading or conceptual label.',
  '- Do not put a global Data flow or Pipeline summary in `skill_description` or `skill_overview`; operation details must live only inside their own removable operation sections.',
  '',
  'Fidelity policy:',
  '- The full generated bundle should be high-recall and detailed enough for a future solver to reconstruct the standard implementation behavior from the skill.',
  '- Prefer preserving implementation-critical details over being concise.',
  '- Preserve constants, axis orders, reshape rules, FFT conventions, normalization factors, coordinate origins, crop windows, dtype conversions, bounds, smoothing, clipping, stopping criteria, file naming, and output schema rules.',
  '- Do not collapse the whole implementation into one vague reference operation.',
  '- Do not replace task-specific knowledge with generic advice.',
  '',
  'Atomic operation definition:',
  'An atomic operation is the smallest coherent action or convention whose removal creates a meaningful ablation variant. Each operation must:',
  '- Represent one task-relevant action, formula, convention, validation, or reusable tool.',
  '- Be independently removable through its `SKILL.md` anchor and owned resource/script files.',
  '- Have enough context to be usable when enabled.',
  '- Avoid bundling unrelated concepts together.',
  '- Avoid splitting tightly coupled equations into fragments that cannot be used independently.',
  '- Appear at least once in `skill_md`.',
  '- Belong to a directed acyclic graph of knowledge dependencies.',
  '- Depend only on earlier operations in the returned `operations` array.',
  '- Fit a layered hierarchy: contract/data/conventions -> model/operators -> solver/objective -> output/validation/probes.',
  '',
  'Good operation boundaries include:',
  '- Public contract extraction.',
  '- Case metadata and array loading.',
  '- Unit conversion or dtype convention.',
  '- Coordinate origin, axis order, crop, padding, or scan geometry convention.',
  '- Forward model or physical equation.',
  '- Objective/loss and regularization.',
  '- Solver initialization.',
  '- One optimization/update step family.',
  '- Runtime probe or cheap smoke test.',
  '- Post-processing and output schema writing.',
  '- Submission validation.',
  '',
  'Resource/script policy:',
  '- Use `resources/op_NNN_slug.md` for formulas, tables, pseudocode, implementation notes, and compact code excerpts.',
  '- Use `scripts/op_NNN_slug.py` only for reusable deterministic helpers, probes, validators, or converters.',
  '- Scripts must be self-contained, run from the eval run root, avoid package installation, and avoid private/source paths.',
  '- An operation section may reference only its own assets or assets from declared dependencies.',
  '- If two operations need shared knowledge, either create a dependency operation or duplicate the small needed note.',
  '- Do not reference another operation id, resource, or script unless that operation is the current operation or a declared dependency.',
  '',
  'Ablation policy:',
  '- All generated operations should default to enabled.',
  '- Greedy ablation tries operations directly by `ablation_priority` from high to low, regardless of dependency shape.',
  '- Assign higher priority to likely redundant scaffolding, diagnostics, or guardrails.',
  '- Assign lower priority to likely critical formulas, data conventions, coordinate conventions, and output semantics.',
  '- Use `depends_on` only as manifest metadata for human audit; it does not control deletion order or cascade deletion.',
  '',
  'Output requirements:',
  '- Return exactly one final response through the StructuredOutput tool.',
  '- Do not return Markdown as the final answer.',
  '- The StructuredOutput value must match the provided JSON schema.',
  `- The draft should target ${RECOMMENDED_MIN_ORACLE_OPERATIONS}-${DEFAULT_MAX_ORACLE_OPERATIONS} operations for nontrivial tasks; use fewer only if the implementation is genuinely simple.`,
  `- The draft must never exceed ${DEFAULT_MAX_ORACLE_OPERATIONS} atomic operations.`,
].join('\n')

export type OracleSkillAuthorUserPromptInput = {
  taskId: string
  taskDir: string
  skillName: string
  authorWorkspace: string
  readmeExcerpt: string
  outputSchemaExcerpt: string
  visibleCasesExcerpt: string
  publicFileManifest: string
  standardSourceManifest: string
  maxOperations?: number
}

export function buildOracleSkillAuthorUserPrompt(
  input: OracleSkillAuthorUserPromptInput,
): string {
  return [
    'Generate an ablatable oracle skill draft for the task below.',
    '',
    '<authoring_context>',
    `task_id: ${input.taskId}`,
    `task_dir: ${input.taskDir}`,
    `skill_name: ${input.skillName}`,
    `author_workspace: ${input.authorWorkspace}`,
    'operation_id_format: op_NNN_short_slug',
    `default_operation_count: ${RECOMMENDED_MIN_ORACLE_OPERATIONS}-${input.maxOperations ?? DEFAULT_MAX_ORACLE_OPERATIONS} for nontrivial tasks`,
    `max_operation_count: ${input.maxOperations ?? DEFAULT_MAX_ORACLE_OPERATIONS}`,
    'dependency_graph: directed acyclic graph; every depends_on target must appear earlier in operations',
    '</authoring_context>',
    '',
    '<allowed_read_roots>',
    `- ${input.taskDir}/README.md`,
    `- ${input.taskDir}/output_schema.json`,
    `- ${input.taskDir}/visible_data/`,
    `- ${input.taskDir}/std_code/`,
    '</allowed_read_roots>',
    '',
    '<allowed_write_roots>',
    `- ${input.authorWorkspace}`,
    '</allowed_write_roots>',
    '',
    '<public_materials>',
    `<readme path="${input.taskDir}/README.md">`,
    input.readmeExcerpt || '(missing)',
    '</readme>',
    '',
    `<output_schema path="${input.taskDir}/output_schema.json">`,
    input.outputSchemaExcerpt || '{}',
    '</output_schema>',
    '',
    `<visible_cases path="${input.taskDir}/visible_data/cases.json">`,
    input.visibleCasesExcerpt || '{}',
    '</visible_cases>',
    '',
    '<public_file_manifest>',
    input.publicFileManifest || '(none)',
    '</public_file_manifest>',
    '</public_materials>',
    '',
    '<standard_implementation_manifest>',
    'The following files are privileged authoring input. Inspect them with Read/Grep/Glob as needed. Use them to extract implementation knowledge, but do not expose original provenance, private paths, or forbidden tokens in solver-facing skill files.',
    '',
    input.standardSourceManifest || '(none)',
    '</standard_implementation_manifest>',
    '',
    'Required workflow:',
    '1. Inspect the public materials and record the future solver\'s public task contract.',
    '2. Inspect the standard implementation entry points first, then follow imports/functions needed for the algorithm.',
    '3. Identify exact data loading, formulas, geometry conventions, solver steps, initialization, post-processing, validation, and output writing.',
    '4. Decompose those details into atomic operations suitable for deletion ablation.',
    '5. For every operation, produce `id`, `kind`, `title`, `depends_on`, `ablation_priority`, `enabled_by_default: true`, `source_refs`, `skill_md`, owned `resources`, and owned `scripts`.',
    '6. Make critical task-specific conventions separate operations when their removal should be experimentally testable.',
    '7. Put every operation\'s essential instruction in `skill_md`; resources/scripts may add detail but cannot be the only place the operation exists.',
    '8. Avoid one giant source-summary operation.',
    '9. Avoid generic advice unless it is necessary to apply extracted implementation knowledge.',
    '10. Ensure the operation list is a layered directed acyclic graph with dependencies pointing only backward.',
    '11. Ensure `skill_md`, resources, and scripts do not contain forbidden solver-facing tokens.',
    '',
    'Return the completed draft through StructuredOutput.',
  ].join('\n')
}

export function buildOracleSkillRepairPrompt(issues: ValidationIssue[] | unknown): string {
  return [
    'The oracle skill draft failed host-side validation. Produce a corrected complete draft through StructuredOutput.',
    '',
    '<validation_errors>',
    JSON.stringify(issues, null, 2),
    '</validation_errors>',
    '',
    'Correction rules:',
    '- Return the full corrected draft, not a patch.',
    '- Preserve useful operations from the previous draft unless they caused a validation or safety issue.',
    '- Fix every listed issue.',
    '- Keep operation IDs stable when possible.',
    '- Ensure every operation appears in `skill_md`.',
    '- Ensure every resource/script path is relative, owned by the operation, and under `resources/` or `scripts/`.',
    '- Keep operation dependencies as a directed acyclic graph and make every dependency point to an earlier operation.',
    `- Keep the draft at or below ${DEFAULT_MAX_ORACLE_OPERATIONS} atomic operations.`,
    '- Ensure solver-facing content contains no forbidden tokens: `std_code`, `.judge_private`, `ground_truth`, `reference_outputs`, or `private_judge`.',
    '- Do not write final files yourself. Return StructuredOutput only.',
  ].join('\n')
}
